routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PersonasController@index');
Route::post('/puesto', 'PersonasController@AjaxRequestPuestos')->name('Puestos');
Route::post('/estacionamiento', 'PersonasController@AjaxRequestEstacionamiento')->name('Estacionamiento');
Route::post('/marca', 'PersonasController@AjaxRequestMarcas')->name('marca');
Route::post('/pais', 'PersonasController@AjaxRequestPais')->name('Pais');
Route::post('/estado', 'PersonasController@AjaxRequestEstado')->name('Estado');
Route::post('/municipio', 'PersonasController@AjaxRequestMunicipio')->name('Municipio');
Route::get('/detalle_ruta/{id}', 'PersonasController@rutas')->name('rutas');
Route::get('/central_maps/{id}', 'PostulanteController@create')->name('post');
Route::resource('postulantes', 'PostulanteController');
Route::get('/vacantes/{id}/postulados', 'VacanteController@postulados')->name('vacantes.postulados');
Route::post('/vacantes/{id}/postulados', 'VacanteController@actualizaPostulado')->name('Actualiza');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');

    Route::resource('vacantes', 'VacanteController');

    Route::resource('rols', 'RolController');

    Route::resource('puestos', 'PuestoController');

    Route::resource('permisos', 'PermisoController');

    Route::resource('logs', 'LogController');

    Route::resource('gerentes', 'GerenteController');

    Route::resource('marcas', 'MarcaController');

    Route::resource('proyectos', 'ProyectoController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 * @package App\Models
 * @version August 22, 2019, 2:58 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection logs
 * @property \Illuminate\Database\Eloquent\Collection roles
 * @property \Illuminate\Database\Eloquent\Collection vacantes
 * @property string name
 * @property string email
 * @property string|\Carbon\Carbon email_verified_at
 * @property string password
 * @property string remember_token
 */
class User extends Authenticatable
{

    use Notifiable;
    public $table = 'users';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'email' => 'required',
        'password' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function logs()
    {
        return $this->hasMany(\App\Models\Log::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function roles()
    {
        return $this->hasMany(\App\Models\Role::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function vacantes()
    {
        return $this->hasMany(\App\Models\Vacante::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Permiso;
use App\Models\Rol;
use App\Models\User;
use App\Repositories\UserRepository;
use Flash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Response;

class UserController extends AppBaseController
{
    /** @var  UserRepository */
    private $userRepository;

    public function __construct(UserRepository $userRepo)
    {
        $this->userRepository = $userRepo;
    }

    /**
     * Display a listing of the User.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $users = DB::table('users')
            ->join('roles', 'users.id', '=', 'roles.id_user')
            ->join('permisos', 'roles.id_permiso', '=', 'permisos.id')
            ->select('users.id', 'users.name', 'users.email', 'permisos.nombre')
            ->get();
        return view('users.index')
            ->with('users', $users);
    }

    /**
     * Show the form for creating a new User.
     *
     * @return Response
     */
    public function create()
    {
        $permisos = Permiso::all();
        return view('users.create')
            ->with('permiso', $permisos);
    }

    /**
     * Store a newly created User in storage.
     *
     * @param CreateUserRequest $request
     *
     * @return Response
     */
    public function store()
    {
        $input = request()->validate([
            'permiso' => ['required'],
            'password' => ['required'],
            'email' => ['required'],
            'name' => ['required'],
        ]);
        $input['password'] = Hash::make($input['password']);
        $user = $this->userRepository->create($input);
        $rol = new Rol;
        $rol->id_user = $user->id;
        $rol->id_permiso = $input['permiso'];
        $rol->save();
        Flash::success('User saved successfully.');

        return redirect(route('users.index'));
    }

    /**
     * Display the specified User.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $user = $this->userRepository->find($id);

        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }

        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $user = DB::table('users')
            ->join('roles', 'users.id', '=', 'roles.id_user')
            ->join('permisos', 'roles.id_permiso', '=', 'permisos.id')
            ->where('users.id', '=', $id)
            ->select('users.*', 'permisos.nombre')
            ->get();
        if (empty($user[0])) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }
        $permisos = Permiso::all();
        return view('users.edit')
            ->with('user', $user[0])
            ->with('permiso', $permisos);
    }

    /**
     * Update the specified User in storage.
     *
     * @param int $id
     * @param UpdateUserRequest $request
     *
     * @return Response
     */
    public function update($id)
    {
        $user = $this->userRepository->find($id);
        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }
        $input = \request()->validate([
            'permiso' => ['required'],
            'password' => [''],
            'email' => ['required'],
            'name' => ['required'],
        ]);
        if ($input['password'] == null) {
            $user2 = User::find($id);
            $user2->name = $input['name'];
            $user2->email = $input['email'];
            $user2->save();
            $rol = DB::table('roles')
                ->where('id_user', '=', $id)
                ->get();
            $roles = Rol::find($rol[0]->id);
            $roles->id_permiso = $input['permiso'];
            $roles->save();
        } else {
            $input['password'] = Hash::make($input['password']);
            $user = $this->userRepository->update($input, $id);
            $rol = DB::table('roles')
                ->where('id_user', '=', $id)
                ->get();
            $roles = Rol::find($rol[0]->id);
            $roles->id_permiso = $input['permiso'];
            $roles->save();
        }

        Flash::success('User updated successfully.');

        return redirect(route('users.index'));
    }

    /**
     * Remove the specified User from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $user = $this->userRepository->find($id);

        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }

        $this->userRepository->delete($id);

        Flash::success('User deleted successfully.');

        return redirect(route('users.index'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Nuevo Usuario</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
            {!! Form::open(['route' => 'users.store']) !!}
                @include('users.fields')
            {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Usuario</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch']) !!}
                @include('users.fields')
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/users/fields.blade.php
<!-- Name Field -->
<div class="md-form">
    <i class="fas fa-user prefix"></i>
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="md-form">
    <i class="fas fa-envelope prefix"></i>
    {!! Form::label('email', 'Correo:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>


<!-- Password Field -->
<div class="md-form">
    <i class="fas fa-unlock-alt prefix"></i>
    {!! Form::label('password', 'Contraseña:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>

<!-- Permiso Field-->
<div class="md-form">
    <i class="fas fa-unlock-alt prefix"></i>
    {!! Form::label('password', 'Confirmar Contraseña:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>

<!--Blue select-->
<select class="mdb-select md-form colorful-select dropdown-success" name="permiso">
    <option value="" selected disabled>Seleccione un perfil</option>
    @forelse($permiso as $item)
        <option value="{{$item->id}}">{{$item->nombre}}</option>
    @empty
        <option value="">Sin permisos</option>
    @endforelse
</select>

<!--/Blue select-->

<!-- Submit Field -->
<div class="md-form">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('users.index') !!}" class="btn btn-default">Cancelar</a>
</div>

@push('scripts')
    $(document).ready(function() {
    $('.mdb-select').materialSelect();
    });
@endpush

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Usuarios</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row">
            <div class="col-6">
                <button type="button" class="btn btn-default btn-lg">
                    Usuarios encontrados: <span class="counter badge badge-danger ml-4"></span>
                </button>
            </div>
            <div class="col-3 text-right">
                <a type="button" class="btn btn-primary btn-rounded" href="{!! route('permisos.index') !!}">
                    Permisos
                </a>
            </div>
            <div class="col-3 text-right">
                <a type="button" class="btn btn-dark btn-rounded" href="{!! route('users.create') !!}">
                    Agregar Usuario
                </a>
            </div>
        </div>
        <br>
        <div class="form-group pull-right">
            <input type="text" class="search form-control" placeholder="¿Que estas buscando?">
        </div>
        @include('users.table')
    </section>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('users.show_fields')
                    <a href="{!! route('users.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $user->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $user->name !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $user->email !!}</p>
</div>

<!-- Email Verified At Field -->
<div class="form-group">
    {!! Form::label('email_verified_at', 'Email Verified At:') !!}
    <p>{!! $user->email_verified_at !!}</p>
</div>

<!-- Password Field -->
<div class="form-group">
    {!! Form::label('password', 'Password:') !!}
    <p>{!! $user->password !!}</p>
</div>

<!-- Remember Token Field -->
<div class="form-group">
    {!! Form::label('remember_token', 'Remember Token:') !!}
    <p>{!! $user->remember_token !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $user->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $user->updated_at !!}</p>
</div>

resources/views/users/table.blade.php
<div class="table-responsive">
    <table class="table table-hover table-bordered results responsive-table text-center" id="users-table">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Rol</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{!! $user->name !!}</td>
                <td>{!! $user->email !!}</td>
                <td>{!! $user->nombre !!}</td>
                <td>
                    {!! Form::open(['route' => ['users.destroy', $user->id], 'method' => 'delete']) !!}
                    <a href="{!! route('users.edit', [$user->id]) !!}"
                       class='btn btn-default btn-xs white-text'>visualizar</a>
                    {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Estas seguro?')"]) !!}

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
<br><br>