routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PersonasController@index');
Route::post('/puesto', 'PersonasController@AjaxRequestPuestos')->name('Puestos');
Route::post('/estacionamiento', 'PersonasController@AjaxRequestEstacionamiento')->name('Estacionamiento');
Route::post('/marca', 'PersonasController@AjaxRequestMarcas')->name('marca');
Route::post('/pais', 'PersonasController@AjaxRequestPais')->name('Pais');
Route::post('/estado', 'PersonasController@AjaxRequestEstado')->name('Estado');
Route::post('/municipio', 'PersonasController@AjaxRequestMunicipio')->name('Municipio');
Route::get('/detalle_ruta/{id}', 'PersonasController@rutas')->name('rutas');
Route::get('/central_maps/{id}', 'PostulanteController@create')->name('post');
Route::resource('postulantes', 'PostulanteController');
Route::get('/vacantes/{id}/postulados', 'VacanteController@postulados')->name('vacantes.postulados');
Route::post('/vacantes/{id}/postulados', 'VacanteController@actualizaPostulado')->name('Actualiza');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');

    Route::resource('vacantes', 'VacanteController');

    Route::resource('rols', 'RolController');

    Route::resource('puestos', 'PuestoController');

    Route::resource('permisos', 'PermisoController');

    Route::resource('logs', 'LogController');

    Route::resource('gerentes', 'GerenteController');

    Route::resource('marcas', 'MarcaController');

    Route::resource('proyectos', 'ProyectoController');
});

app/Models/Marca.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

/**
 * Class Marca
 * @package App\Models
 * @version August 22, 2019, 4:52 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection proyectos
 * @property \Illuminate\Database\Eloquent\Collection
 * @property string marca
 */
class Marca extends Model
{

    public $table = 'marcas';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    public $fillable = [
        'marca'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'marca' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'marca' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function proyectos()
    {
        return $this->hasMany(\App\Models\Proyecto::class);
    }
}

app/Http/Controllers/MarcaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMarcaRequest;
use App\Http\Requests\UpdateMarcaRequest;
use App\Repositories\MarcaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MarcaController extends AppBaseController
{
    /** @var  MarcaRepository */
    private $marcaRepository;

    public function __construct(MarcaRepository $marcaRepo)
    {
        $this->marcaRepository = $marcaRepo;
    }

    /**
     * Display a listing of the Marca.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $marcas = $this->marcaRepository->all();

        return view('marcas.index')
            ->with('marcas', $marcas);
    }

    /**
     * Show the form for creating a new Marca.
     *
     * @return Response
     */
    public function create()
    {
        return view('marcas.create');
    }

    /**
     * Store a newly created Marca in storage.
     *
     * @param CreateMarcaRequest $request
     *
     * @return Response
     */
    public function store(CreateMarcaRequest $request)
    {
        $input = $request->all();

        $marca = $this->marcaRepository->create($input);

        Flash::success('Marca agregada satisfactoriamente.');

        return redirect(route('marcas.index'));
    }

    /**
     * Display the specified Marca.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $marca = $this->marcaRepository->find($id);

        if (empty($marca)) {
            Flash::error('Marca not found');

            return redirect(route('marcas.index'));
        }

        return view('marcas.show')->with('marca', $marca);
    }

    /**
     * Show the form for editing the specified Marca.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $marca = $this->marcaRepository->find($id);

        if (empty($marca)) {
            Flash::error('Marca no encontrada');

            return redirect(route('marcas.index'));
        }

        return view('marcas.edit')->with('marca', $marca);
    }

    /**
     * Update the specified Marca in storage.
     *
     * @param int $id
     * @param UpdateMarcaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMarcaRequest $request)
    {
        $marca = $this->marcaRepository->find($id);

        if (empty($marca)) {
            Flash::error('Marca no encontrada');

            return redirect(route('marcas.index'));
        }

        $marca = $this->marcaRepository->update($request->all(), $id);

        Flash::success('Marca actualizada correctamente.');

        return redirect(route('marcas.index'));
    }

    /**
     * Remove the specified Marca from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $marca = $this->marcaRepository->find($id);

        if (empty($marca)) {
            Flash::error('Marca no encontrada');

            return redirect(route('marcas.index'));
        }

        $this->marcaRepository->delete($id);

        Flash::success('Marca eliminada correctamente.');

        return redirect(route('marcas.index'));
    }
}

resources/views/marcas/create.blade.php
@extends('layouts.app')
@section('title','Marcas')
@section('content')
    <div class="card card-cascade wilder">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header default-color">
            <!-- Title -->
            <h3 class="card-header-title">Añadir marca</h3>
        </div>
    </div>
    <hr>

    <div class="col-12">
        @include('layouts.errors')

        {!! Form::open(['route' => 'marcas.store']) !!}
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                @include('marcas.fields')
            </div>
        </div>
        {!! Form::close() !!}
    </div>
    <div class="col-4">

    </div>
    </div>
@endsection

resources/views/marcas/edit.blade.php
@extends('layouts.app')
@section('title','Marcas')
@section('content')
    <div class="card card-cascade wilder">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header default-color">
            <!-- Title -->
            <h3 class="card-header-title">Editar marca</h3>
        </div>
    </div>
    <hr>

    <div class="row justify-content-md-center">
        <div class="col-md-8">
            @include('layouts.errors')

            {!! Form::model($marca, ['route' => ['marcas.update', $marca->id], 'method' => 'patch']) !!}

            @include('marcas.fields')
            {!! Form::close() !!}
        </div>
    </div>

@endsection

resources/views/marcas/fields.blade.php
<!-- Marca Field -->
<div class="md-form">
    {!! Form::label('marca', 'Marca:') !!}
    {!! Form::text('marca', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="md-form">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('marcas.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/marcas/index.blade.php
@extends('layouts.app')
@section('title','Marcas')
@section('content')
    <div class="card card-cascade wilder">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header default-color">
            <!-- Title -->
            <h3 class="card-header-title">Marcas</h3>
        </div>
    </div>
    <hr>
    @include('flash::message')


    <div class="row">
        <div class="col-6">
            <button type="button" class="btn btn-default btn-lg">
                Marcas encontradas: <span class="counter badge badge-danger ml-4"></span>
            </button>
        </div>
        <div class="col-3 text-right">
            <a type="button" class="btn btn-primary btn-rounded" href="{!! route('proyectos.index') !!}">
                Proyectos
            </a>
        </div>
        <div class="col-3 text-right">
            <a type="button" class="btn btn-dark btn-rounded" href="{!! route('marcas.create') !!}">
                Agregar Marca
            </a>
        </div>

    </div>
    <br>
    <!-- Empieza tabla -->
    @include('marcas.table')
    <!--Termina tabla-->


    <br><br>
@endsection

resources/views/marcas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Marca
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('marcas.show_fields')
                    <a href="{!! route('marcas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/marcas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $marca->id !!}</p>
</div>

<!-- Marca Field -->
<div class="form-group">
    {!! Form::label('marca', 'Marca:') !!}
    <p>{!! $marca->marca !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $marca->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $marca->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $marca->deleted_at !!}</p>
</div>

resources/views/marcas/table.blade.php
<div class="table-responsive ">
    <div class="form-group pull-right">
        <input type="text" class="search form-control" placeholder="¿Que estas buscando?">
    </div>
    <table class="table table-hover table-bordered results responsive-table text-center ">
        <thead>
        <tr>
            <th>Marca</th>
            <th>Acción</th>

        </tr>
        <tr class="warning no-result">
            <td colspan="12" style="color:red; font-size: 20px;"><i class="fa fa-warning"></i> No se encontro
                registro con la información ingresada
            </td>
        </tr>
        </thead>

        <tbody>
        @foreach($marcas as $marca)
            <tr>
                <td>{!! $marca->marca !!}</td>
                <td>
                    {!! Form::open(['route' => ['marcas.destroy', $marca->id], 'method' => 'delete']) !!}

                        <a href="{!! route('marcas.edit', [$marca->id]) !!}" class='btn btn-default btn-xs white-text'><i
                                    class="glyphicon glyphicon-edit"></i>EDITAR</a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>ELIMINAR', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Estas seguro?')"]) !!}

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>