routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PersonasController@index');
Route::post('/puesto', 'PersonasController@AjaxRequestPuestos')->name('Puestos');
Route::post('/estacionamiento', 'PersonasController@AjaxRequestEstacionamiento')->name('Estacionamiento');
Route::post('/marca', 'PersonasController@AjaxRequestMarcas')->name('marca');
Route::post('/pais', 'PersonasController@AjaxRequestPais')->name('Pais');
Route::post('/estado', 'PersonasController@AjaxRequestEstado')->name('Estado');
Route::post('/municipio', 'PersonasController@AjaxRequestMunicipio')->name('Municipio');
Route::get('/detalle_ruta/{id}', 'PersonasController@rutas')->name('rutas');
Route::get('/central_maps/{id}', 'PostulanteController@create')->name('post');
Route::resource('postulantes', 'PostulanteController');
Route::get('/vacantes/{id}/postulados', 'VacanteController@postulados')->name('vacantes.postulados');
Route::post('/vacantes/{id}/postulados', 'VacanteController@actualizaPostulado')->name('Actualiza');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');

    Route::resource('vacantes', 'VacanteController');

    Route::resource('rols', 'RolController');

    Route::resource('puestos', 'PuestoController');

    Route::resource('permisos', 'PermisoController');

    Route::resource('logs', 'LogController');

    Route::resource('gerentes', 'GerenteController');

    Route::resource('marcas', 'MarcaController');

    Route::resource('proyectos', 'ProyectoController');
});

app/Models/Permiso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

/**
 * Class Permiso
 * @package App\Models
 * @version August 22, 2019, 3:03 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection roles
 * @property string nombre
 */
class Permiso extends Model
{

    public $table = 'permisos';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    public $fillable = [
        'nombre'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nombre' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function roles()
    {
        return $this->hasMany(\App\Models\Role::class);
    }
}

app/Http/Controllers/PermisoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePermisoRequest;
use App\Http\Requests\UpdatePermisoRequest;
use App\Repositories\PermisoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class PermisoController extends AppBaseController
{
    /** @var  PermisoRepository */
    private $permisoRepository;

    public function __construct(PermisoRepository $permisoRepo)
    {
        $this->permisoRepository = $permisoRepo;
    }

    /**
     * Display a listing of the Permiso.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $permisos = $this->permisoRepository->all();

        return view('permisos.index')
            ->with('permisos', $permisos);
    }

    /**
     * Show the form for creating a new Permiso.
     *
     * @return Response
     */
    public function create()
    {
        return view('permisos.create');
    }

    /**
     * Store a newly created Permiso in storage.
     *
     * @param CreatePermisoRequest $request
     *
     * @return Response
     */
    public function store(CreatePermisoRequest $request)
    {
        $input = $request->all();

        $permiso = $this->permisoRepository->create($input);

        Flash::success('Permiso saved successfully.');

        return redirect(route('permisos.index'));
    }

    /**
     * Display the specified Permiso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $permiso = $this->permisoRepository->find($id);

        if (empty($permiso)) {
            Flash::error('Permiso not found');

            return redirect(route('permisos.index'));
        }

        return view('permisos.show')->with('permiso', $permiso);
    }

    /**
     * Show the form for editing the specified Permiso.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $permiso = $this->permisoRepository->find($id);

        if (empty($permiso)) {
            Flash::error('Permiso not found');

            return redirect(route('permisos.index'));
        }

        return view('permisos.edit')->with('permiso', $permiso);
    }

    /**
     * Update the specified Permiso in storage.
     *
     * @param int $id
     * @param UpdatePermisoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePermisoRequest $request)
    {
        $permiso = $this->permisoRepository->find($id);

        if (empty($permiso)) {
            Flash::error('Permiso not found');

            return redirect(route('permisos.index'));
        }

        $permiso = $this->permisoRepository->update($request->all(), $id);

        Flash::success('Permiso updated successfully.');

        return redirect(route('permisos.index'));
    }

    /**
     * Remove the specified Permiso from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $permiso = $this->permisoRepository->find($id);

        if (empty($permiso)) {
            Flash::error('Permiso not found');

            return redirect(route('permisos.index'));
        }

        $this->permisoRepository->delete($id);

        Flash::success('Permiso deleted successfully.');

        return redirect(route('permisos.index'));
    }
}

resources/views/permisos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Nuevo Permiso</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {!! Form::open(['route' => 'permisos.store']) !!}
                @include('permisos.fields')
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/permisos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Permiso
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($permiso, ['route' => ['permisos.update', $permiso->id], 'method' => 'patch']) !!}

                    @include('permisos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/permisos/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('permisos.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/permisos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Permisos</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row">
            <div class="col-6">
                <button type="button" class="btn btn-default btn-lg">
                    Usuarios encontrados: <span class="counter badge badge-danger ml-4"></span>
                </button>
            </div>
            <div class="col-3 text-right">
                <a type="button" class="btn btn-primary btn-rounded" href="{!! route('users.index') !!}">
                    Usuarios
                </a>
            </div>
            <div class="col-3 text-right">
                <a type="button" class="btn btn-dark btn-rounded" href="{!! route('permisos.create') !!}">
                    Agregar Permiso
                </a>
            </div>
        </div>
        <br>
        <div class="form-group pull-right">
            <input type="text" class="search form-control" placeholder="¿Que estas buscando?">
        </div>
        @include('permisos.table')
    </section>
@endsection

resources/views/permisos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Permiso
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('permisos.show_fields')
                    <a href="{!! route('permisos.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/permisos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $permiso->id !!}</p>
</div>

<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{!! $permiso->nombre !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $permiso->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $permiso->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $permiso->deleted_at !!}</p>
</div>

resources/views/permisos/table.blade.php
<div class="table-responsive">
    <table class="table" id="permisos-table">
        <thead>
        <tr>
            <th>Nombre</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($permisos as $permiso)
            <tr>
                <td>{!! $permiso->nombre !!}</td>
                <td>
                    {!! Form::open(['route' => ['users.destroy', $permiso->id], 'method' => 'delete']) !!}

                    <a href="{!! route('users.edit', [$permiso->id]) !!}"
                       class='btn btn-default btn-xs white-text'>visualizar</a>

                    {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Estas seguro?')"]) !!}

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>