routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PersonasController@index');
Route::post('/puesto', 'PersonasController@AjaxRequestPuestos')->name('Puestos');
Route::post('/estacionamiento', 'PersonasController@AjaxRequestEstacionamiento')->name('Estacionamiento');
Route::post('/marca', 'PersonasController@AjaxRequestMarcas')->name('marca');
Route::post('/pais', 'PersonasController@AjaxRequestPais')->name('Pais');
Route::post('/estado', 'PersonasController@AjaxRequestEstado')->name('Estado');
Route::post('/municipio', 'PersonasController@AjaxRequestMunicipio')->name('Municipio');
Route::get('/detalle_ruta/{id}', 'PersonasController@rutas')->name('rutas');
Route::get('/central_maps/{id}', 'PostulanteController@create')->name('post');
Route::resource('postulantes', 'PostulanteController');
Route::get('/vacantes/{id}/postulados', 'VacanteController@postulados')->name('vacantes.postulados');
Route::post('/vacantes/{id}/postulados', 'VacanteController@actualizaPostulado')->name('Actualiza');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');

    Route::resource('vacantes', 'VacanteController');

    Route::resource('rols', 'RolController');

    Route::resource('puestos', 'PuestoController');

    Route::resource('permisos', 'PermisoController');

    Route::resource('logs', 'LogController');

    Route::resource('gerentes', 'GerenteController');

    Route::resource('marcas', 'MarcaController');

    Route::resource('proyectos', 'ProyectoController');
});

app/Models/Proyecto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

/**
 * Class Proyecto
 * @package App\Models
 * @version September 2, 2019, 4:12 pm UTC
 *
 * @property \App\Models\Gerente idGerente
 * @property \App\Models\Marca idMarca
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection vacantes
 * @property integer id_gerente
 * @property integer id_marca
 * @property string nombre
 * @property string direccion
 * @property string pais
 * @property string edo_prov
 * @property string mun_cd
 * @property string colonia
 * @property string calles
 * @property string numeroExt
 * @property string cp
 * @property string latitud
 * @property string longitud
 * @property boolean status
 * @property integer num_vac
 * @property string foto
 * @property boolean escuela
 * @property integer no_est
 */
class Proyecto extends Model
{

    public $table = 'proyectos';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    public $fillable = [
        'id_gerente',
        'id_marca',
        'nombre',
        'direccion',
        'pais',
        'edo_prov',
        'mun_cd',
        'colonia',
        'calles',
        'numeroExt',
        'cp',
        'latitud',
        'longitud',
        'status',
        'num_vac',
        'foto',
        'escuela',
        'no_est'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_gerente' => 'integer',
        'id_marca' => 'integer',
        'nombre' => 'string',
        'direccion' => 'string',
        'pais' => 'string',
        'edo_prov' => 'string',
        'mun_cd' => 'string',
        'colonia' => 'string',
        'calles' => 'string',
        'numeroExt' => 'string',
        'cp' => 'string',
        'latitud' => 'string',
        'longitud' => 'string',
        'status' => 'boolean',
        'num_vac' => 'integer',
        'foto' => 'string',
        'escuela' => 'boolean',
        'no_est' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_gerente' => 'required',
        'id_marca' => 'required',
        'nombre' => 'required',
        'direccion' => 'required',
        'pais' => 'required',
        'edo_prov' => 'required',
        'mun_cd' => 'required',
        'colonia' => 'required',
        'calles' => 'required',
        'numeroExt' => 'required',
        'cp' => 'required',
        'latitud' => 'required',
        'longitud' => 'required',
        'status' => 'required',
        'num_vac' => 'required',
        'foto' => 'required',
        'escuela' => 'required',
        'no_est' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idGerente()
    {
        return $this->belongsTo(\App\Models\Gerente::class, 'id_gerente');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idMarca()
    {
        return $this->belongsTo(\App\Models\Marca::class, 'id_marca');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function vacantes()
    {
        return $this->hasMany(\App\Models\Vacante::class);
    }
}

app/Http/Controllers/ProyectoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProyectoRequest;
use App\Http\Requests\UpdateProyectoRequest;
use App\Models\Gerente;
use App\Models\Marca;
use App\Models\Proyecto;
use App\Repositories\ProyectoRepository;
use Flash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Response;

class ProyectoController extends AppBaseController
{
    /** @var  ProyectoRepository */
    private $proyectoRepository;

    public function __construct(ProyectoRepository $proyectoRepo)
    {
        $this->proyectoRepository = $proyectoRepo;
    }

    /**
     * Display a listing of the Proyecto.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $proyectos = DB::table('proyectos')
            ->join('gerentes', 'gerentes.id', '=', 'proyectos.id_gerente')
            ->select('proyectos.id', 'proyectos.nombre', 'proyectos.direccion', 'gerentes.nombre as gerente', 'proyectos.escuela')
            ->get();
        return view('proyectos.index')
            ->with('proyectos', $proyectos);
    }

    /**
     * Show the form for creating a new Proyecto.
     *
     * @return Response
     */
    public function create()
    {
        $gerentes = Gerente::all();
        $marcas = Marca::all();
        return view('proyectos.create')
            ->with('gerentes', $gerentes)
            ->with('marcas', $marcas);
    }

    /**
     * Store a newly created Proyecto in storage.
     *
     * @param CreateProyectoRequest $request
     *
     * @return Response
     */
    public function store()
    {
        /*$input = request()->all();
        dd($input);*/
        $input = request()->validate([
            "nombre" => ['required'],
            "pais" => ['required',],
            "edo_prov" => ['required'],
            "mun_cd" => ['required'],
            "colonia" => ['required'],
            "calles" => ['required'],
            "numeroExt" => ['required'],
            "cp" => ['required'],
            "num_vac" => ['required'],
            "gerente" => ['required'],
            "marca" => ['required'],
            "direccion" => ['required'],
            "latitud" => ['required'],
            "longitud" => ['required'],
            "escuela" => ['required'],
            'no_est' => ['required']
        ]);
        $foto = request()->file('file');
        $dataImg = $foto->get();
        $img = base64_encode($dataImg);
        $proyecto = new Proyecto();
        if ($input['escuela'] == 'true') {
            $proyecto->fill([
                'id_gerente' => $input['gerente'],
                'id_marca' => $input['marca'],
                'nombre' => $input['nombre'],
                'direccion' => $input['direccion'],
                'pais' => strtoupper($input['pais']),
                'edo_prov' => strtoupper($input['edo_prov']),
                'mun_cd' => strtoupper($input['mun_cd']),
                'colonia' => strtoupper($input['colonia']),
                'calles' => strtoupper($input['calles']),
                'numeroExt' => strtoupper($input['numeroExt']),
                'cp' => $input['cp'],
                'latitud' => $input['latitud'],
                'longitud' => $input['longitud'],
                'status' => 1,
                'num_vac' => $input['num_vac'],
                'foto' => $img,
                'escuela' => true,
                'no_est' => $input['no_est']
            ]);
        } else {
            $proyecto->fill([
                'id_gerente' => $input['gerente'],
                'id_marca' => $input['marca'],
                'nombre' => $input['nombre'],
                'direccion' => $input['direccion'],
                'pais' => strtoupper($input['pais']),
                'edo_prov' => strtoupper($input['edo_prov']),
                'mun_cd' => strtoupper($input['mun_cd']),
                'colonia' => strtoupper($input['colonia']),
                'calles' => strtoupper($input['calles']),
                'numeroExt' => strtoupper($input['numeroExt']),
                'cp' => $input['cp'],
                'latitud' => $input['latitud'],
                'longitud' => $input['longitud'],
                'status' => 1,
                'num_vac' => $input['num_vac'],
                'foto' => $img,
                'escuela' => false,
                'no_est' => $input['no_est']
            ]);
        }
        $proyecto->save();
        /*$proyecto = $this->proyectoRepository->create($input);*/

        Flash::success('Proyecto añadido satisfactoriamente.');

        return redirect(route('proyectos.index'));
    }

    /**
     * Display the specified Proyecto.
     *
     * @param int $id
     *
     * @return Response
     */


    public function show($id)
    {
        $proyecto = $this->proyectoRepository->find($id);

        if (empty($proyecto)) {
            Flash::error('Proyecto no encontrado');

            return redirect(route('proyectos.index'));
        }

        return view('proyectos.show')->with('proyecto', $proyecto);
    }

    /**
     * Show the form for editing the specified Proyecto.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $proyecto = DB::table('proyectos')
            ->join('gerentes', 'proyectos.id_gerente', '=', 'gerentes.id')
            ->join('marcas', 'proyectos.id_marca', '=', 'marcas.id')
            ->select('proyectos.*', 'gerentes.nombre as gerente', 'marcas.marca')
            ->where('proyectos.id', '=', $id)
            ->get();
        $gerentes = Gerente::all();
        $marcas = Marca::all();
        if (empty($proyecto)) {
            Flash::error('Proyecto no encontrado');

            return redirect(route('proyectos.index'));
        }
        return view('proyectos.edit')
            ->with('proyecto', $proyecto[0])
            ->with('gerentes', $gerentes)
            ->with('marcas', $marcas);
    }

    /**
     * Update the specified Proyecto in storage.
     *
     * @param int $id
     * @param UpdateProyectoRequest $request
     *
     * @return Response
     */
    public function update($id)
    {
        $input = request()->validate([
            "nombre" => ['required'],
            "pais" => ['required',],
            "edo_prov" => ['required'],
            "mun_cd" => ['required'],
            "colonia" => ['required'],
            "calles" => ['required'],
            "numeroExt" => ['required'],
            "cp" => ['required'],
            "gerente" => [''],
            "marca" => [''],
            "direccion" => ['required'],
            "latitud" => ['required'],
            "longitud" => ['required'],
            "escuela" => [''],
            'no_est' => ['required']
        ]);
        $proyecto = $this->proyectoRepository->find($id);
        if (empty($proyecto)) {
            Flash::error('Proyecto no encontrado');

            return redirect(route('proyectos.index'));
        }
        $proyecto->nombre = $input['nombre'];
        $proyecto->direccion = $input['direccion'];
        $proyecto->pais = $input['pais'];
        $proyecto->edo_prov = $input['edo_prov'];
        $proyecto->mun_cd = $input['mun_cd'];
        $proyecto->colonia = $input['colonia'];
        $proyecto->calles = $input['calles'];
        $proyecto->numeroExt = $input['numeroExt'];
        $proyecto->cp = $input['cp'];
        $proyecto->latitud = $input['latitud'];
        $proyecto->longitud = $input['longitud'];
        $proyecto->no_est = $input['no_est'];
        if (is_numeric($input['gerente'])) {
            $proyecto->id_gerente = $input['gerente'];
        }
        if (is_numeric($input['marca'])) {
            $proyecto->id_marca = $input['marca'];
        }
        if ($input['escuela'] == 'true') {
            $proyecto->escuela = true;
        } elseif ($input['escuela'] == 'false') {
            $proyecto->escuela = false;
        }
        $foto = request()->file('file');
        if ($foto != null) {
            $dataImg = file_get_contents($foto->getLinkTarget());
            $img = base64_encode($dataImg);
            $proyecto->foto = $img;
        }
        $proyecto->save();

        Flash::success('Proyecto actualizado satisfactoriamente.');

        return redirect(route('proyectos.index'));
    }

    /**
     * Remove the specified Proyecto from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $proyecto = $this->proyectoRepository->find($id);

        if (empty($proyecto)) {
            Flash::error('Proyecto no encontrado');

            return redirect(route('proyectos.index'));
        }

        $this->proyectoRepository->delete($id);

        Flash::success('Proyecto eliminado satisfactoriamente.');

        return redirect(route('proyectos.index'));
    }
}

resources/views/proyectos/create.blade.php
@extends('layouts.app')
@section('title','proyectos')
@section('content')
    <style>#map_canvas {
            display: none
        }</style>
    <style>#guardar {
            display: none
        }</style>
    <div class="card card-cascade wilder">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header default-color">
            <!-- Title -->
            <h3 class="card-header-title">Añadir Estacionamiento</h3>
        </div>
    </div>
    <hr>

    <div class="col-12">
        @include('layouts.errors')
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                {!! Form::open(['route' => 'proyectos.store' , 'enctype' => 'multipart/form-data']) !!}
                @include('proyectos.fields')
                {!! Form::close() !!}
            </div>
            <div class="col-md-6">
                <!-- Card -->
                <div class="card map-card">
                    <!--Google map-->
                    <div id="map_canvas" class="z-depth-1-half map-container" style="height: 500px"></div>
                    <!-- Card content -->
                    <div class="card-body closed px-0">
                        <div class="button px-2 mt-3">
                            <a class="btn-floating btn-lg btn-default float-right"><i class="fas fa-parking"></i></a>
                        </div>
                        <div class="white px-4 pb-4 pt-3-5">
                            <!-- Title -->
                            <h5 class="card-title h5 living-coral-text" id="proyecto">Proyecto</h5>
                            <hr>
                            <table class="table table-borderless">
                                <tbody>
                                <tr>
                                    <th scope="row" class="px-0 pb-3 pt-2">
                                        <i class="fas fa-map-marker-alt living-coral-text"></i>
                                    </th>
                                    <td class="pb-3 pt-2"><h5>Dirección:</h5>
                                        <span id="calle">....</span>
                                        <span id="num_ext"></span>
                                        <p id="colonia_id"></p>
                                        <span id="codigop"></span>
                                        <span id="pais_id"></span>
                                        <span>,</span>
                                        <span id="estado_id"></span>
                                    </td>

                                </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <!-- Card -->
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{asset('js/createproject.js')}}"></script>

@endsection

<script>

    @push('scripts')
    //Variables
    var map = null;
    var infoWindow = null;
    var resultados_lat = "";
    var resultados_long = "";
    var direc = "";
    var mensajeError = "";

    $(document).ready(function () {
        //input de nombre
        $("#nombre").keyup(function () {
            var value = $(this).val();
            $("#proyecto").text(value);
        });

        //input de direccion
        $("#calles").keyup(function () {
            var value = $(this).val();
            $("#calle").text(value);
        });

        //input de numero exterior
        $("#numeroexterior").keyup(function () {
            var value = $(this).val();
            $("#num_ext").text(value);
        });

        //input de colonia
        $("#colonia").keyup(function () {
            var value = $(this).val();
            $("#colonia_id").text(value);
        });

        //input de codigo postal
        $("#codigo").keyup(function () {
            var value = $(this).val();
            $("#codigop").text(value);
        });

        //input de pais
        $("#pais").keyup(function () {
            var value = $(this).val();
            $("#pais_id").text(value);
        });

        //input de estado
        $("#estado").keyup(function () {
            var value = $(this).val();
            $("#estado_id").text(value);
        });

    });

    //Script para Validar datos y Mostrar mapa
    $('#boton01').click(function () {
        if ($('#nombre').val() === '' || $('#calles').val() === '' || $('#numeroexterior').val() === '' || $('#colonia').val() === '' || $('#codigo').val() === '' || $('#estado').val() === '' || $('#pais').val() === '') {
            alert('Hay campos sin completar');
            $('#map_canvas').hidden();
        } else {
            direc = $("#calles").val() + " " + $("#numeroexterior").val() + ", " + $("#colonia").val() + ", " + $("#codigo").val() + ", " + $("#estado").val() + " " + $("#pais").val() + " ";
            $("#direccion").val(direc);
            $('#map_canvas').show();
            initialize();
        }
    });

    //Codigo Para generar Mapa

    //Se hace peticion de mapa
    function initialize() {
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'address': direc}, function (results, status) {
            if (status === 'OK') {
                var resultados = results[0].geometry.location,
                    resultados_lat = resultados.lat(),
                    resultados_long = resultados.lng();
                //alert("Latitud: " +resultados_lat + " longitud: " + resultados_long);
                $("#latitud").val(resultados_lat);
                $("#longitud").val(resultados_long);
                positionMap(resultados_lat, resultados_long);
                //Se muestra el boton de guardar
                $('#guardar').show();
            } else {
                if (status === "ZERO_RESULTS") {
                    mensajeError = "No hubo resultados para la dirección ingresada.";
                } else if (status === "OVER_QUERY_LIMIT" || status === "REQUEST_DENIED" || status === "UNKNOWN_ERROR") {
                    mensajeError = "Error general del mapa.";
                } else if (status === "INVALID_REQUEST") {
                    mensajeError = "Error de la web. Contacte con Name Agency.";
                }
                alert(mensajeError);
            }
        });
    }

    function positionMap(latd, long) {
        var myLatlng = {lat: latd, lng: long};

        var image = {

            url: '{{asset('logo/logo/marker-central-2.png')}}',
            // This marker is 20 pixels wide by 32 pixels high.
            size: new google.maps.Size(25, 25),
            // The origin for this image is (0, 0).
            origin: new google.maps.Point(0, 0),
            // The anchor for this image is the base of the flagpole at (0, 32).
            anchor: new google.maps.Point(14, 30)
        };


        var myOptions = {
            zoom: 13,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);

        infoWindow = new google.maps.InfoWindow();

        var marker = new google.maps.Marker({
            position: myLatlng,
            draggable: true,
            icon: image,
            map: map,
            title: 'Ejemplo marcador arrastrable'
        });
        google.maps.event.addListener(marker, 'drag', function () {
            openInfoWindow2(marker);
        });
        google.maps.event.addListener(marker, 'dragend', function () {
            openInfoWindow(marker);
        });
    }

    function openInfoWindow(marker) {
        var markerLatLng = marker.getPosition();
        infoWindow.setContent([
            'La posicion del marcador es: ',
            markerLatLng.lat(),
            ', ',
            markerLatLng.lng(),
            ' Arrastrame y haz click para actualizar la posición.'
        ].join(''));
        infoWindow.open(map, marker);
        var geocoder = new google.maps.Geocoder();

        geocoder.geocode({'latLng': marker.getPosition()}, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                console.log(results);
                var address = results[0]['formatted_address'];
                $("#direccion").val(address);
                var componente = results[0]['address_components'];
                console.log(componente);
                $('#colonia').val(componente[2]['long_name']);
                $('#colonia_id').text(componente[2]['long_name']);
                $('#calles').val(componente[1]['long_name']);
                $("#calle").text(componente[1]['long_name']);
                $('#numeroexterior').val(componente[0]['long_name']);
                $('#num_ext').text(componente[0]['long_name']);
                $('#codigo').val(componente[6]['long_name']);
                $('#codigop').text(componente[6]['long_name']);
            }
        });
    }

    function openInfoWindow2(marker) {
        var markerLatLng = marker.getPosition();
        $("#latitud").val(markerLatLng.lat());
        $("#longitud").val(markerLatLng.lng());
    }

    @endpush

</script>

resources/views/proyectos/edit_table.blade.php
<!-- Nombre Field -->
<div class="md-form">
    <i class="far fa-address-card prefix"></i>
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Direccion Field -->
<div class="md-form">
    <i class="fas fa-directions prefix"></i>
    {!! Form::label('direccion', 'Direccion:') !!}
    {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
</div>

<!-- Pais Field -->
<div class="md-form">
    <i class="fas fa-city prefix"></i>
    {!! Form::label('pais', 'País:') !!}
    {!! Form::text('pais', null, ['class' => 'form-control']) !!}
</div>

<!-- Edo Prov Field -->
<div class="md-form">
    <i class="fas fa-map-marked-alt prefix"></i>
    {!! Form::label('edo_prov', 'Estado/Provincia:') !!}
    {!! Form::text('edo_prov', null, ['class' => 'form-control']) !!}
</div>

<!-- Mun Cd Field -->
<div class="md-form">
    <i class="fas fa-map-signs prefix"></i>
    {!! Form::label('mun_cd', 'Municipio:') !!}
    {!! Form::text('mun_cd', null, ['class' => 'form-control']) !!}
</div>

<!-- Colonia Field -->
<div class="md-form">
    <i class="fas fa-map-pin prefix"></i>
    {!! Form::label('colonia', 'Colonia:') !!}
    {!! Form::text('colonia', null, ['class' => 'form-control']) !!}
</div>


<!-- Calles Field -->
<div class="md-form">
    <i class="fas fa-road prefix"></i>
    {!! Form::label('calles', 'Calles:') !!}
    {!! Form::text('calles', null, ['class' => 'form-control']) !!}
</div>

<!-- Numeroext Field -->
<div class="md-form">
    <i class="fas fa-map-marker prefix"></i>
    {!! Form::label('numeroExt', 'Numeroext:') !!}
    {!! Form::text('numeroExt', null, ['class' => 'form-control']) !!}
</div>

<!-- Cp Field -->
<div class="md-form">
    <i class="fas fa-map-marker-alt prefix"></i>
    {!! Form::label('cp', 'Cp:') !!}
    {!! Form::text('cp', null, ['class' => 'form-control']) !!}
</div>

<!-- Latitud Field -->
<!--<div class="md-form">
    {!! Form::label('latitud', 'Latitud:') !!}
{!! Form::text('latitud', null, ['class' => 'form-control']) !!}
        </div>

        <div class="md-form">
{!! Form::label('longitud', 'Longitud:') !!}
{!! Form::text('longitud', null, ['class' => 'form-control']) !!}
        </div>-->

<!-- Status Field -->
<!--<div class="md-form">
    <i class="far fa-lightbulb prefix"></i>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="materialChecked2" checked>
        <label class="form-check-label" for="materialChecked2">Material checked</label>
    </div>
</div>-->

<!-- Num Vac Field -->
<div class="md-form">
    <i class="fas fa-list-ol prefix"></i>
    {!! Form::label('num_vac', 'Num Vac:') !!}
    {!! Form::number('num_vac', null, ['class' => 'form-control']) !!}
</div>

<!-- Foto Field -->
<div class="md-form">
    <div class="file-field">
        <div class="btn btn-primary btn-sm float-left">
            <span>Examinar equipo</span>
            <input type="file" name="file" id="file"
                   accept="image/*">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate"  type="text" placeholder="Cargar archivo">
        </div>
    </div>

</div>

<!-- Escuela Field -->
<!--<div class="md-form">
    {!! Form::label('escuela', 'Escuela:') !!}
        <label class="checkbox-inline">
{!! Form::hidden('escuela', 0) !!}
{!! Form::checkbox('escuela', '1', null) !!} 1
    </label>
</div>
-->
<!--Gerentes select-->
<select class="mdb-select md-form colorful-select dropdown-success" searchable="Buscar...">
    <option value="" selected disabled>Seleccione un gerente</option>
    @forelse($gerentes as $item)
        <option value="{{$item->id}}">{{$item->nombre}}</option>
    @empty
        <option value="">Sin Gerentes</option>
    @endforelse
</select>

<!--Marcas select-->
<select class="mdb-select md-form colorful-select dropdown-success" searchable="Buscar...">
    <option value="" selected disabled>Seleccione una Marca</option>
    @forelse($marcas as $item)
        <option value="{{$item->id}}">{{$item->marca}}</option>
    @empty
        <option value="">Sin marcas</option>
    @endforelse
</select>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('proyectos.index') !!}" class="btn btn-default">Cancelar</a>
</div>
<br>
<br>

@push('scripts')
    $(document).ready(function() {
    $('.mdb-select').materialSelect();
    });
@endpush

resources/views/proyectos/index.blade.php
@extends('layouts.app')
@section('title','Proyectos')
@section('content')
    <div class="card card-cascade wilder">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header default-color">
            <!-- Title -->
            <h3 class="card-header-title">Estacionamientos</h3>
        </div>
    </div>
    <hr>
    @include('flash::message')


    <div class="row">
        <div class="col-6">
            <button type="button" class="btn btn-default btn-lg">
                Estacionamientos encontrados: <span class="counter badge badge-danger ml-4"></span>
            </button>
        </div>
        <div class="col-3 text-right">
            <a type="button" class="btn btn-primary btn-rounded" href="{!! route('marcas.index') !!}">
                Marcas
            </a>
        </div>
        <div class="col-3 text-right">
            <a type="button" class="btn btn-dark btn-rounded" href="{!! route('proyectos.create') !!}">
                Agregar Estacionamiento
            </a>
        </div>

    </div>
    <br>
    <!-- Empieza tabla -->
    @include('proyectos.table')
    <!--Termina tabla-->


    <br><br>
@endsection

<script>
    @push('scripts')
    $(function () {
        $('.material-tooltip-main').tooltip({
            template: '<div class="tooltip md-tooltip-main"><div class="tooltip-arrow md-arrow"></div><div class="tooltip-inner md-inner-main"></div></div>'
        });
    })
    @endpush
</script>

resources/views/proyectos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Proyecto
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('proyectos.show_fields')
                    <a href="{!! route('proyectos.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection